/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import BLL_BusinessLogicLayer.DoiTacManager;
import Controller.controllerDoiTac;
import DBConnection.ConnectSQLServer;
import Model.modelDoiTac;
import Model.modelKhachHang;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class LayoutDoiTac extends javax.swing.JFrame {
    private DoiTacManager dtManager = new DoiTacManager();
    /**
     * Creates new form LayoutDoiTac
     */
    public LayoutDoiTac() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadDoiTacData();

        controllerDoiTac DoiTacEvent = new controllerDoiTac(this);
        this.btn_Resert.addActionListener(DoiTacEvent);
        this.btn_Sua.addActionListener(DoiTacEvent);
        this.btn_Xoa.addActionListener(DoiTacEvent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel50 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tb_DoiTac = new javax.swing.JTable();
        KhungThongTin = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txt_ChuThich = new javax.swing.JTextArea();
        txt_tenNhaPhanPhoi = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_matKhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_MaDoiTac = new javax.swing.JTextField();
        panel_NutBam = new javax.swing.JPanel();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Resert = new javax.swing.JButton();
        txt_TimKiemTen = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel50.setText("Đối Tác");

        tb_DoiTac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đối tác", "Tên đối tác", "SĐT", "Địa chỉ", "Mật khẩu", "Email", "Chú thích"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_DoiTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb_DoiTacMousePressed(evt);
            }
        });
        jScrollPane13.setViewportView(tb_DoiTac);

        jLabel52.setText("Tên nhà phân phối");

        jLabel53.setText("Địa chỉ");

        jLabel54.setText("SĐT");

        jLabel55.setText("Email");

        jLabel56.setText("Chú thích");

        txt_ChuThich.setColumns(20);
        txt_ChuThich.setRows(5);
        jScrollPane14.setViewportView(txt_ChuThich);

        txt_tenNhaPhanPhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenNhaPhanPhoiActionPerformed(evt);
            }
        });

        jLabel1.setText("Mật khẩu");

        jLabel2.setText("Mã Nhà Cung Cấp");

        javax.swing.GroupLayout KhungThongTinLayout = new javax.swing.GroupLayout(KhungThongTin);
        KhungThongTin.setLayout(KhungThongTinLayout);
        KhungThongTinLayout.setHorizontalGroup(
            KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhungThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(KhungThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tenNhaPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KhungThongTinLayout.createSequentialGroup()
                        .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addComponent(jLabel56)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel55)
                            .addComponent(jLabel54))
                        .addGap(60, 60, 60)
                        .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(txt_DiaChi)
                                .addComponent(txt_MaDoiTac)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        KhungThongTinLayout.setVerticalGroup(
            KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhungThongTinLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MaDoiTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(txt_tenNhaPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(KhungThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56))
                .addGap(28, 28, 28))
        );

        btn_Xoa.setText("Xoá");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Resert.setText("Resert");
        btn_Resert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_NutBamLayout = new javax.swing.GroupLayout(panel_NutBam);
        panel_NutBam.setLayout(panel_NutBamLayout);
        panel_NutBamLayout.setHorizontalGroup(
            panel_NutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NutBamLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_Xoa)
                .addGap(142, 142, 142)
                .addComponent(btn_Sua)
                .addGap(103, 103, 103)
                .addComponent(btn_Resert)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        panel_NutBamLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Resert, btn_Sua, btn_Xoa});

        panel_NutBamLayout.setVerticalGroup(
            panel_NutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NutBamLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_NutBamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sua)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_Resert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_TimKiem.setText("Tìm Kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_NutBam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(txt_TimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(btn_TimKiem)))
                        .addGap(19, 19, 19)
                        .addComponent(KhungThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TimKiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_NutBam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(KhungThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearInformation(){
        txt_MaDoiTac.setText("");
        txt_tenNhaPhanPhoi.setText("");
        txt_DiaChi.setText("");
        txt_SDT.setText("");
        txt_matKhau.setText("");
        txt_Email.setText("");
        txt_ChuThich.setText("");
        tb_DoiTac.clearSelection(); // Bỏ chọn dòng trong bảng
    }
    
    public void loadDoiTacData() {
        try {
            DefaultTableModel model = (DefaultTableModel)this.tb_DoiTac.getModel();
            
            model.setRowCount(0);
            for(modelDoiTac dt : dtManager.getDoiTac()){
                model.addRow(new Object[]{dt.getMaDoiTac() , dt.getTenDoiTac(),dt.getSdt(),dt.getDiaChi() , dt.getMatKhau() ,dt.getEmail() , dt.getChuThich()});
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi tải dữ liệu");
        }
    }
    
    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed

    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_ResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResertActionPerformed
        

    }//GEN-LAST:event_btn_ResertActionPerformed

    private void txt_tenNhaPhanPhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenNhaPhanPhoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenNhaPhanPhoiActionPerformed

    private void tb_DoiTacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DoiTacMousePressed
        DefaultTableModel model = (DefaultTableModel) this.tb_DoiTac.getModel();
        
        int selected = this.tb_DoiTac.getSelectedRow();
        
        if(selected != -1){
            this.txt_MaDoiTac.setText(this.tb_DoiTac.getValueAt(selected, 0).toString());
            this.txt_tenNhaPhanPhoi.setText(this.tb_DoiTac.getValueAt(selected, 1).toString());
            this.txt_SDT.setText(this.tb_DoiTac.getValueAt(selected, 2).toString());
            this.txt_DiaChi.setText(this.tb_DoiTac.getValueAt(selected, 3).toString());
            this.txt_matKhau.setText(this.tb_DoiTac.getValueAt(selected, 4).toString());
            this.txt_Email.setText(this.tb_DoiTac.getValueAt(selected, 5).toString());
            this.txt_ChuThich.setText(this.tb_DoiTac.getValueAt(selected, 6).toString());
        }
    }//GEN-LAST:event_tb_DoiTacMousePressed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.tb_DoiTac.getModel()  ;
        String tenKh = this.txt_tenNhaPhanPhoi.getText().trim();
        try {
            ArrayList<modelDoiTac> list =  dtManager.TimKiem(tenKh);
            model.setRowCount(0);
            
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(null, "Không tìm thầy tên đối tác");
            }else{
                for(modelDoiTac dt : list){
                    model.addRow(new Object[]{dt.getMaDoiTac() , dt.getTenDoiTac(),dt.getSdt(),dt.getDiaChi() , dt.getMatKhau() ,dt.getEmail() , dt.getChuThich()});
                }
            }
            this.txt_tenNhaPhanPhoi.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KhungThongTin;
    private javax.swing.JButton btn_Resert;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JPanel panel_NutBam;
    private javax.swing.JTable tb_DoiTac;
    public javax.swing.JTextArea txt_ChuThich;
    public javax.swing.JTextField txt_DiaChi;
    public javax.swing.JTextField txt_Email;
    public javax.swing.JTextField txt_MaDoiTac;
    public javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TimKiemTen;
    public javax.swing.JTextField txt_matKhau;
    public javax.swing.JTextField txt_tenNhaPhanPhoi;
    // End of variables declaration//GEN-END:variables
}
