/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import BLL_BusinessLogicLayer.SanPhamManager;
import DBConnection.ConnectSQLServer;
import Model.modelSanPham;
import Controller.controllerSanPham;
import java.awt.Dimension;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class LayoutSanPham extends javax.swing.JFrame {
    private SanPhamManager spManager = new SanPhamManager();
    /**
     * Creates new form LayoutSanPham
     */
    public LayoutSanPham() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        loadDataToTable();
        
        controllerSanPham eventSanPham = new controllerSanPham(this);
        this.btn_SanPham_Xoa.addActionListener(eventSanPham);
        this.btn_SanPham_Sua.addActionListener(eventSanPham);
        this.btn_SanPham_Resert.addActionListener(eventSanPham);
        
        
    }
    
    public void clearDataForSanPham(){
        this.txt_SanPham_maSanPham.setText("");
        this.txt_SanPham_tenSanPham.setText("");
        this.txt_SanPham_GiaBan.setText("");
        this.txt_SanPham_TonKho.setText("");
        this.txt_MaDanhMuc.setText("");
        this.txt_LinkAnh.setText("");
        
    }
    
    // tải dữ liệu lên bảng
    public void loadDataToTable(){
        try {
            DefaultTableModel model = (DefaultTableModel)this.tb_SanPham.getModel();
            model.setRowCount(0);
            
            for(modelSanPham sp : spManager.getSanPham()){
                model.addRow(new Object[]{sp.getMaSP() , sp.getTenSanPham() ,sp.getGiaBan() , sp.getSoLuongHienCon() , sp.getMaDM() , sp.getLinkAnh()});
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi tải dữ liệu lên bảng");
        }
    }
    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nhom = new javax.swing.ButtonGroup();
        LayoutSanPham = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_SanPham = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_SanPham_maSanPham = new javax.swing.JTextField();
        txt_SanPham_tenSanPham = new javax.swing.JTextField();
        txt_SanPham_GiaBan = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_SanPham_TonKho = new javax.swing.JTextField();
        lb_SanPham_DonVi = new javax.swing.JLabel();
        btn_SanPham_Sua = new javax.swing.JButton();
        btn_SanPham_Xoa = new javax.swing.JButton();
        btn_SanPham_Resert = new javax.swing.JButton();
        btn_SanPham_DoiAnh = new javax.swing.JButton();
        txt_LinkAnh = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_MaDanhMuc = new javax.swing.JTextField();
        panel_linkAnh = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Giá Bán", "Số Lượng Hiện Còn", "Mã Danh Mục", "Ảnh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb_SanPhamMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(tb_SanPham);

        jLabel1.setText("Mã Sản Phẩm");

        jLabel15.setText("Tên Sản Phẩm");

        jLabel20.setText("Tồn Kho");

        btn_SanPham_Sua.setText("Sửa");

        btn_SanPham_Xoa.setText("Xoá");
        btn_SanPham_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SanPham_XoaActionPerformed(evt);
            }
        });

        btn_SanPham_Resert.setText("Resert");

        btn_SanPham_DoiAnh.setText("Đổi Ảnh");

        jLabel23.setText("Tìm Kiếm");

        jLabel2.setText("Giá Bán");

        jLabel3.setText("Mã Danh Mục");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_SanPham_DonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(453, 453, 453))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(btn_SanPham_Resert))
                    .addComponent(txt_SanPham_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_SanPham_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(txt_SanPham_tenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_MaDanhMuc))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(txt_SanPham_maSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel20)
                                    .addGap(40, 40, 40)
                                    .addComponent(txt_SanPham_TonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(78, 78, 78)
                            .addComponent(btn_SanPham_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_LinkAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btn_SanPham_DoiAnh)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_SanPham_maSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(btn_SanPham_Sua)))
                            .addComponent(txt_SanPham_TonKho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(btn_SanPham_Xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_SanPham_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(btn_SanPham_Resert)
                        .addGap(34, 34, 34)
                        .addComponent(lb_SanPham_DonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btn_SanPham_DoiAnh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txt_SanPham_tenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(txt_MaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_LinkAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(panel_linkAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(panel_linkAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Sản Phẩm", jPanel1);

        javax.swing.GroupLayout LayoutSanPhamLayout = new javax.swing.GroupLayout(LayoutSanPham);
        LayoutSanPham.setLayout(LayoutSanPhamLayout);
        LayoutSanPhamLayout.setHorizontalGroup(
            LayoutSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutSanPhamLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        LayoutSanPhamLayout.setVerticalGroup(
            LayoutSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LayoutSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LayoutSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SanPham_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SanPham_XoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SanPham_XoaActionPerformed

    private void tb_SanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_SanPhamMousePressed
        DefaultTableModel model = (DefaultTableModel) this.tb_SanPham.getModel();
        DecimalFormat df = new DecimalFormat("#######.#");
        int selected = this.tb_SanPham.getSelectedRow();

        if (selected != -1) {
            String maSP = this.tb_SanPham.getValueAt(selected, 0).toString();
            String tenSP = this.tb_SanPham.getValueAt(selected, 1).toString();
            String giaBan = this.tb_SanPham.getValueAt(selected, 2).toString();
            String soLuongHienCon = this.tb_SanPham.getValueAt(selected, 3).toString();
            String maDanhMuc = this.tb_SanPham.getValueAt(selected,4).toString();
            String linkAnh = this.tb_SanPham.getValueAt(selected, 5).toString();

            this.txt_SanPham_maSanPham.setText(maSP);
            this.txt_SanPham_tenSanPham.setText(tenSP);
            this.txt_SanPham_GiaBan.setText(df.format(Double.parseDouble(giaBan)));
            this.txt_SanPham_TonKho.setText(soLuongHienCon);
            this.txt_MaDanhMuc.setText(maDanhMuc);
            this.txt_LinkAnh.setText(linkAnh);
            
            try {
                URL urlAnh = new URL(linkAnh);
                ImageIcon icon = new ImageIcon(urlAnh);
                Dimension panelSize = this.panel_linkAnh.getSize();
                Image scaledImage = icon.getImage().getScaledInstance(panelSize.width, panelSize.height, Image.SCALE_SMOOTH);
                JLabel lblImage = new JLabel(new ImageIcon(scaledImage));

                this.panel_linkAnh.removeAll();
                this.panel_linkAnh.add(lblImage);
                this.panel_linkAnh.revalidate();
                this.panel_linkAnh.repaint();
            } catch (Exception e) {
                System.err.println("Lỗi khi tải ảnh: " + e.getMessage()); // In ra thông báo lỗi
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tb_SanPhamMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LayoutSanPham;
    private javax.swing.ButtonGroup Nhom;
    private javax.swing.JButton btn_SanPham_DoiAnh;
    private javax.swing.JButton btn_SanPham_Resert;
    private javax.swing.JButton btn_SanPham_Sua;
    private javax.swing.JButton btn_SanPham_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lb_SanPham_DonVi;
    private javax.swing.JPanel panel_linkAnh;
    private javax.swing.JTable tb_SanPham;
    public javax.swing.JTextField txt_LinkAnh;
    public javax.swing.JTextField txt_MaDanhMuc;
    public javax.swing.JTextField txt_SanPham_GiaBan;
    public javax.swing.JTextField txt_SanPham_TonKho;
    public javax.swing.JTextField txt_SanPham_maSanPham;
    public javax.swing.JTextField txt_SanPham_tenSanPham;
    // End of variables declaration//GEN-END:variables
}
