/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import BLL_BusinessLogicLayer.ChiTietHoaDonManager;
import BLL_BusinessLogicLayer.PhieuMuaHangManager;
import Model.modelChiTietHoaDon;
import DBConnection.ConnectSQLServer;
import Model.modelPhieuMuaHang;
import Controller.controllerChiTietHoaDon;
import Controller.controllerPhieuMuaHang;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

/**
 *
 * @author Hieu
 */
public class LayoutHoaDon extends javax.swing.JFrame {
    private PhieuMuaHangManager phieuMuaHangManager = new PhieuMuaHangManager();
    private ChiTietHoaDonManager chiTietHoaDonManager = new ChiTietHoaDonManager();
    /**
     * Creates new form LayoutHoaDon
     */
    public LayoutHoaDon() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        loadDataPhieuMuaHangToTable();
        loadDataChiTietHoaDonToTable();
        
        
        controllerPhieuMuaHang eventHoaDon = new controllerPhieuMuaHang(this);
        this.btn_tb1_Resert.addActionListener(eventHoaDon);
        this.btn_tb1_Sua.addActionListener(eventHoaDon);
        this.btn_tb1_Xoa.addActionListener(eventHoaDon);
        
        
        controllerChiTietHoaDon eventChiTietHoaDon = new controllerChiTietHoaDon(this);
        this.btn_tb2_Resert.addActionListener(eventChiTietHoaDon);
        this.btn_tb2_Xoa.addActionListener(eventChiTietHoaDon);
        this.btn_tb2_Sua.addActionListener(eventChiTietHoaDon);
        
    }
    
    
    
    // làm sạch dữ liệu
    public void clearDataForPhieuMuaHang(){
        this.txt_tb1_maHoaDon.setText("");
        this.txt_tb1_MaKhachHang.setText("");
        this.txt_tb1_NgayLap.setText("");
        this.txt_tb1_Email.setText("");
        this.txt_tb1_SDT.setText("");
        this.txt_tb1_NguoiNhan.setText("");
        this.txt_tb1_DiaChi.setText("");
    }
    public void clearDataForChiTietHoaDon(){
        this.txt_tb2_DonGia.setText("");
        this.txt_tb2_SoLuong.setText("");
        this.txt_tb2_MaSize.setText("");
        this.txt_tb2_maHoaDon.setText("");
        this.txt_tb2_tenSanPham.setText("");
    }
    
    // đưa dữ liệu lên bảng PhieuMuaHang
    public void loadDataPhieuMuaHangToTable(){
        try {
            DefaultTableModel defaut = (DefaultTableModel)this.tb_HoaDon_PhieuMuaHang.getModel();
            defaut.setRowCount(0);
            for(modelPhieuMuaHang pmh : phieuMuaHangManager.getPhieuMuaHang()){
                defaut.addRow(new Object[]{pmh.getMaDH() , pmh.getKHno(), pmh.getNgayTaoDH() , pmh.getDiaChi() , pmh.getEmail() , pmh.getSdt(), pmh.getNguoiNhan()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tải dữ liệu phiếu mua hàng lên thất bại");
            e.printStackTrace();
        }
    }
    
    // đưa dữ liệu bleen bảng ChiTietHoaDon
    public void loadDataChiTietHoaDonToTable(){
        try {
            DefaultTableModel model = (DefaultTableModel) this.tb_HoaDon_ChiTietHoaDon.getModel();
            model.setRowCount(0);
            for(modelChiTietHoaDon cthd : chiTietHoaDonManager.getChiTietHoaDon()){
                model.addRow(new Object[]{cthd.getMaHD() , cthd.getTenSP() , cthd.getMaSize() , cthd.getSoLuongDat() ,cthd.getDonGia() });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tải dữ liệu chi tiết hoá đơn lên thất bại");
            e.printStackTrace();
        }
    }
   
    
    
    
    
   
    
   
    
      
     
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayoutHoaDon = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_HoaDon_PhieuMuaHang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_HoaDon_ChiTietHoaDon = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_tb1_maHoaDon = new javax.swing.JTextField();
        txt_tb1_NgayLap = new javax.swing.JTextField();
        txt_tb1_Email = new javax.swing.JTextField();
        btn_tb1_Sua = new javax.swing.JButton();
        btn_tb1_Xoa = new javax.swing.JButton();
        btn_tb1_Resert = new javax.swing.JButton();
        txt_tb1_MaKhachHang = new javax.swing.JTextField();
        txt_tb1_DiaChi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_tb1_SDT = new javax.swing.JTextField();
        txt_tb1_NguoiNhan = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_tb2_maHoaDon = new javax.swing.JTextField();
        txt_tb2_SoLuong = new javax.swing.JTextField();
        txt_tb2_MaSize = new javax.swing.JTextField();
        btn_tb2_Xoa = new javax.swing.JButton();
        btn_tb2_Sua = new javax.swing.JButton();
        btn_tb2_Resert = new javax.swing.JButton();
        txt_tb2_tenSanPham = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_tb2_DonGia = new javax.swing.JTextField();
        txt_TimKiem_CTHD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_TimKiem_HD = new javax.swing.JButton();
        txt_TimKiem_HD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_HoaDon_PhieuMuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Đơn Hàng", "Mã Khách Hàng", "Ngày Tạo Đơn Hàng", "Địa Chỉ", "Email", "SDT", "Người Nhận"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_HoaDon_PhieuMuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb_HoaDon_PhieuMuaHangMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_HoaDon_PhieuMuaHang);

        jLabel2.setText("CHI TIẾT HOÁ ĐƠN");

        tb_HoaDon_ChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Đơn Hàng", "Mã Sản Phẩm", "Mã Size", "Số Lượng", "Đơn Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_HoaDon_ChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb_HoaDon_ChiTietHoaDonMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb_HoaDon_ChiTietHoaDon);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Mã Hoá Đơn");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 22, -1, -1));

        jLabel4.setText("Mã Khách Hàng");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 59, -1, -1));

        jLabel5.setText("Địa Chỉ");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 96, -1, -1));

        jLabel6.setText("Ngày Lập");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 133, -1, -1));

        jLabel7.setText("Email");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 170, -1, -1));

        txt_tb1_maHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tb1_maHoaDonActionPerformed(evt);
            }
        });
        jPanel7.add(txt_tb1_maHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 130, -1));
        jPanel7.add(txt_tb1_NgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, -1));
        jPanel7.add(txt_tb1_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, -1));

        btn_tb1_Sua.setText("Sửa");
        jPanel7.add(btn_tb1_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 60, -1));

        btn_tb1_Xoa.setText("Xoá");
        jPanel7.add(btn_tb1_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 60, -1));

        btn_tb1_Resert.setText("Resert");
        jPanel7.add(btn_tb1_Resert, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));
        jPanel7.add(txt_tb1_MaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, -1));
        jPanel7.add(txt_tb1_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));

        jLabel8.setText("SĐT");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel9.setText("Người Nhận");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txt_tb1_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tb1_SDTActionPerformed(evt);
            }
        });
        jPanel7.add(txt_tb1_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 110, -1));
        jPanel7.add(txt_tb1_NguoiNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 110, -1));

        jLabel10.setText("Mã Đơn Hàng");

        jLabel11.setText("Mã Sản Phẩm");

        jLabel12.setText("Số lượng");

        jLabel13.setText("Mã Size");

        btn_tb2_Xoa.setText("Xoá");

        btn_tb2_Sua.setText("Sửa");

        btn_tb2_Resert.setText("Resert");

        jLabel1.setText("Đơn Giá");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_tb2_maHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txt_tb2_MaSize)
                            .addComponent(txt_tb2_SoLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_tb2_tenSanPham, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_tb2_DonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tb2_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tb2_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tb2_Resert))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_tb2_maHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tb2_Xoa))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_tb2_tenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_tb2_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_tb2_Sua)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_tb2_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tb2_Resert))
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tb2_MaSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jButton1.setText("Tìm Kiếm");

        btn_TimKiem_HD.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(txt_TimKiem_CTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(txt_TimKiem_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_TimKiem_HD)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel2)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TimKiem_HD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TimKiem_HD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TimKiem_CTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Phiếu Mua Hàng", jPanel5);

        javax.swing.GroupLayout LayoutHoaDonLayout = new javax.swing.GroupLayout(LayoutHoaDon);
        LayoutHoaDon.setLayout(LayoutHoaDonLayout);
        LayoutHoaDonLayout.setHorizontalGroup(
            LayoutHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutHoaDonLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        LayoutHoaDonLayout.setVerticalGroup(
            LayoutHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1342, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LayoutHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(LayoutHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tb1_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tb1_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tb1_SDTActionPerformed

    private void txt_tb1_maHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tb1_maHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tb1_maHoaDonActionPerformed

    private void tb_HoaDon_ChiTietHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_HoaDon_ChiTietHoaDonMousePressed
        DefaultTableModel model = (DefaultTableModel)this.tb_HoaDon_ChiTietHoaDon.getModel();
        int selected = this.tb_HoaDon_ChiTietHoaDon.getSelectedRow();

        if(selected != -1){
            this.txt_tb2_maHoaDon.setText(this.tb_HoaDon_ChiTietHoaDon.getValueAt(selected, 0).toString());
            this.txt_tb2_tenSanPham.setText(this.tb_HoaDon_ChiTietHoaDon.getValueAt(selected, 1).toString());
            this.txt_tb2_MaSize.setText(this.tb_HoaDon_ChiTietHoaDon.getValueAt(selected, 2).toString());
            this.txt_tb2_SoLuong.setText(this.tb_HoaDon_ChiTietHoaDon.getValueAt(selected, 3).toString());
            this.txt_tb2_DonGia.setText(this.tb_HoaDon_ChiTietHoaDon.getValueAt(selected, 4).toString());
        }
    }//GEN-LAST:event_tb_HoaDon_ChiTietHoaDonMousePressed

    private void tb_HoaDon_PhieuMuaHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_HoaDon_PhieuMuaHangMousePressed
        DefaultTableModel model = (DefaultTableModel)this.tb_HoaDon_PhieuMuaHang.getModel();
        int selected = this.tb_HoaDon_PhieuMuaHang.getSelectedRow();

        if(selected != -1 ){
            this.txt_tb1_maHoaDon.setText(this.tb_HoaDon_PhieuMuaHang.getValueAt(selected, 0).toString());
            this.txt_tb1_MaKhachHang.setText(this.tb_HoaDon_PhieuMuaHang.getValueAt(selected, 1).toString());
            this.txt_tb1_NgayLap.setText(this.tb_HoaDon_PhieuMuaHang.getValueAt(selected, 2).toString());
            this.txt_tb1_DiaChi.setText(this.tb_HoaDon_PhieuMuaHang.getValueAt(selected, 3).toString());
            this.txt_tb1_Email.setText(this.tb_HoaDon_PhieuMuaHang.getValueAt(selected, 4).toString());
            this.txt_tb1_SDT.setText(this.tb_HoaDon_PhieuMuaHang.getValueAt(selected, 5).toString());
            this.txt_tb1_NguoiNhan.setText(this.tb_HoaDon_PhieuMuaHang.getValueAt(selected, 6).toString());
        }
    }//GEN-LAST:event_tb_HoaDon_PhieuMuaHangMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LayoutHoaDon;
    private javax.swing.JButton btn_TimKiem_HD;
    private javax.swing.JButton btn_tb1_Resert;
    private javax.swing.JButton btn_tb1_Sua;
    private javax.swing.JButton btn_tb1_Xoa;
    private javax.swing.JButton btn_tb2_Resert;
    private javax.swing.JButton btn_tb2_Sua;
    private javax.swing.JButton btn_tb2_Xoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable tb_HoaDon_ChiTietHoaDon;
    public javax.swing.JTable tb_HoaDon_PhieuMuaHang;
    private javax.swing.JTextField txt_TimKiem_CTHD;
    private javax.swing.JTextField txt_TimKiem_HD;
    public javax.swing.JTextField txt_tb1_DiaChi;
    public javax.swing.JTextField txt_tb1_Email;
    public javax.swing.JTextField txt_tb1_MaKhachHang;
    public javax.swing.JTextField txt_tb1_NgayLap;
    public javax.swing.JTextField txt_tb1_NguoiNhan;
    public javax.swing.JTextField txt_tb1_SDT;
    public javax.swing.JTextField txt_tb1_maHoaDon;
    public javax.swing.JTextField txt_tb2_DonGia;
    public javax.swing.JTextField txt_tb2_MaSize;
    public javax.swing.JTextField txt_tb2_SoLuong;
    public javax.swing.JTextField txt_tb2_maHoaDon;
    public javax.swing.JTextField txt_tb2_tenSanPham;
    // End of variables declaration//GEN-END:variables
}
