/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.btcuoiki_nhom.View;

import Model.modelConnectSQLServer;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class LayoutKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form LayoutKhachHang
     */
    public LayoutKhachHang() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadKhachHangData();
        btn_KhachHang_Them.addActionListener(evt -> btn_KhachHang_ThemActionPerformed(evt));
        btn_KhachHang_Sua.addActionListener(evt -> btn_KhachHang_SuaActionPerformed(evt));
        btn_KhachHang_Xoa.addActionListener(evt -> btn_KhachHang_XoaActionPerformed(evt));
        btn_KhachHang_TimKiem.addActionListener(evt -> btn_KhachHang_TimKiemActionPerformed(evt));
        btn_KhachHang_Resert.addActionListener(evt -> btn_KhachHang_ResertActionPerformed(evt));
            
        this.tb_KhachHang.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                // Chỉ xử lý khi nhấn đúp chuột
                if (tb_KhachHang.getSelectedRow() != -1) {
                    int selected = tb_KhachHang.getSelectedRow();
                    DecimalFormat df = new DecimalFormat("#######.#");

                    String maKH = tb_KhachHang.getValueAt(selected, 0).toString();
                    String tenKH= tb_KhachHang.getValueAt(selected, 1).toString();
                    String SDT = tb_KhachHang.getValueAt(selected, 2).toString();
                    String email = tb_KhachHang.getValueAt(selected, 3).toString();
                    String soDuTaiKhoan = tb_KhachHang.getValueAt(selected, 4).toString();
                    String diaChi = tb_KhachHang.getValueAt(selected, 5).toString();
                    String gioiTinh = tb_KhachHang.getValueAt(selected,6).toString();
                    
                    

                    txt_KhachHang_maKhachHang.setText(maKH);
                    txt_KhachHang_tenKhachHang.setText(tenKH);
                    txt_KhachHang_SDT.setText(SDT);
                    txt_KhachHang_Email.setText(email);
                    txt_KhachHang_soDuTaiKhoan.setText(df.format(Double.parseDouble(soDuTaiKhoan)) + "");
                    txt_KhachHang_DiaChi.setText(diaChi);
                    if (gioiTinh.equalsIgnoreCase("Nam")) {
                        RadioNam.setSelected(true);
                    } else if (gioiTinh.equalsIgnoreCase("Nữ")) {
                        RadioNu.setSelected(true);
                    } else {
                        RadioKhac.setSelected(true);
                    }
                }
                    
             }
         });
    }
    
    private void loadKhachHangData() {
        DefaultTableModel model = (DefaultTableModel) tb_KhachHang.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        try (Connection conn = modelConnectSQLServer.connectSQLServer()) {
            String query = "SELECT maKH ,  tenKH, SDT, Email, soDuTaiKhoan, diaChi, gioiTinh FROM KhachHang";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("maKH"),
                    rs.getString("tenKH"),
                    rs.getString("SDT"),
                    rs.getString("Email"),
                    rs.getDouble("soDuTaiKhoan"),
                    rs.getString("diaChi"),
                    rs.getString("gioiTinh")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGr_GioiTinh = new javax.swing.ButtonGroup();
        LayoutKhachHang = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tb_KhachHang = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        RadioNam = new javax.swing.JRadioButton();
        RadioNu = new javax.swing.JRadioButton();
        RadioKhac = new javax.swing.JRadioButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_KhachHang_DiaChi = new javax.swing.JTextField();
        txt_KhachHang_SDT = new javax.swing.JTextField();
        btn_KhachHang_Them = new javax.swing.JButton();
        btn_KhachHang_Sua = new javax.swing.JButton();
        btn_KhachHang_Xoa = new javax.swing.JButton();
        btn_KhachHang_Resert = new javax.swing.JButton();
        txt_KhachHang_maKhachHang = new javax.swing.JTextField();
        txt_KhachHang_tenKhachHang = new javax.swing.JTextField();
        panel_timKiem = new javax.swing.JPanel();
        txt_KhachHang_TimKiemSDT = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txt_KhachHang_TimKiemTen = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        btn_KhachHang_TimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_KhachHang_soDuTaiKhoan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_KhachHang_Email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel29.setText("Khách Hàng");

        tb_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên khách hàng", "SĐT", "Email", "Số dư tài khoản", "Địa chỉ", "Giới Tính"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tb_KhachHang);

        jLabel30.setText("Mã khách hàng");

        jLabel31.setText("Tên khách hàng");

        jLabel33.setText("Giới tính");

        btnGr_GioiTinh.add(RadioNam);
        RadioNam.setText("nam");

        btnGr_GioiTinh.add(RadioNu);
        RadioNu.setText("Nữ");

        btnGr_GioiTinh.add(RadioKhac);
        RadioKhac.setText("Khác");

        jLabel34.setText("Địa Chỉ");

        jLabel35.setText("SĐT");

        btn_KhachHang_Them.setText("Thêm");
        btn_KhachHang_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHang_ThemActionPerformed(evt);
            }
        });

        btn_KhachHang_Sua.setText("Sửa");
        btn_KhachHang_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHang_SuaActionPerformed(evt);
            }
        });

        btn_KhachHang_Xoa.setText("Xoá");
        btn_KhachHang_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHang_XoaActionPerformed(evt);
            }
        });

        btn_KhachHang_Resert.setText("Resert");
        btn_KhachHang_Resert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHang_ResertActionPerformed(evt);
            }
        });

        jLabel39.setText("SĐT");

        jLabel38.setText("Tên");

        btn_KhachHang_TimKiem.setText("Tìm kiếm");
        btn_KhachHang_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHang_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_timKiemLayout = new javax.swing.GroupLayout(panel_timKiem);
        panel_timKiem.setLayout(panel_timKiemLayout);
        panel_timKiemLayout.setHorizontalGroup(
            panel_timKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_timKiemLayout.createSequentialGroup()
                .addGroup(panel_timKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_timKiemLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panel_timKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_timKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_KhachHang_TimKiemSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_KhachHang_TimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_timKiemLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btn_KhachHang_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panel_timKiemLayout.setVerticalGroup(
            panel_timKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_timKiemLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(btn_KhachHang_TimKiem)
                .addGap(18, 18, 18)
                .addGroup(panel_timKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KhachHang_TimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(28, 28, 28)
                .addGroup(panel_timKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KhachHang_TimKiemSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(83, 83, 83))
        );

        jLabel1.setText("Số dư");

        jLabel2.setText("Email");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(36, 36, 36)
                        .addComponent(RadioNam, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioNu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadioKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_KhachHang_maKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_KhachHang_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_KhachHang_soDuTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_KhachHang_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(30, 30, 30)
                        .addComponent(txt_KhachHang_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_KhachHang_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_KhachHang_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_KhachHang_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_KhachHang_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_KhachHang_Resert, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(panel_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel34)
                    .addComponent(txt_KhachHang_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_KhachHang_maKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txt_KhachHang_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(txt_KhachHang_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_KhachHang_soDuTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_KhachHang_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_KhachHang_Them)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(RadioNam)
                            .addComponent(RadioNu)
                            .addComponent(RadioKhac)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_KhachHang_Xoa)
                        .addGap(29, 29, 29)
                        .addComponent(btn_KhachHang_Resert)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_KhachHang_Sua)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(panel_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout LayoutKhachHangLayout = new javax.swing.GroupLayout(LayoutKhachHang);
        LayoutKhachHang.setLayout(LayoutKhachHangLayout);
        LayoutKhachHangLayout.setHorizontalGroup(
            LayoutKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutKhachHangLayout.createSequentialGroup()
                .addGroup(LayoutKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LayoutKhachHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LayoutKhachHangLayout.createSequentialGroup()
                        .addGap(575, 575, 575)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LayoutKhachHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LayoutKhachHangLayout.setVerticalGroup(
            LayoutKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1177, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LayoutKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(13, Short.MAX_VALUE)
                    .addComponent(LayoutKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KhachHang_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHang_ThemActionPerformed
        try (Connection conn = modelConnectSQLServer.connectSQLServer()) {
            String query = "INSERT INTO KhachHang (tenKH, SDT, Email, soDuTaiKhoan, diaChi, gioiTinh) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, txt_KhachHang_tenKhachHang.getText());
            stmt.setString(2, txt_KhachHang_SDT.getText());
            stmt.setString(3, txt_KhachHang_soDuTaiKhoan.getText());
            stmt.setInt(4, Integer.parseInt(txt_KhachHang_soDuTaiKhoan.getText()));
            stmt.setString(5, txt_KhachHang_DiaChi.getText());
            stmt.setString(6, RadioNam.isSelected() ? "Nam" : (RadioNu.isSelected() ? "Nữ" : "Khác"));
            stmt.executeUpdate();
            loadKhachHangData(); // Cập nhật lại bảng
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_KhachHang_ThemActionPerformed

    private void btn_KhachHang_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHang_SuaActionPerformed
        try (Connection conn = modelConnectSQLServer.connectSQLServer()) {
            String query = "UPDATE KhachHang SET tenKH = ?, SDT = ?, Email = ?, soDuTaiKhoan = ?, diaChi = ?, gioiTinh = ? WHERE maKH = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, txt_KhachHang_tenKhachHang.getText());
            stmt.setString(2, txt_KhachHang_SDT.getText());
            stmt.setString(3, txt_KhachHang_soDuTaiKhoan.getText());
            stmt.setInt(4, Integer.parseInt(txt_KhachHang_soDuTaiKhoan.getText()));
            stmt.setString(5, txt_KhachHang_DiaChi.getText());
            stmt.setString(6, RadioNam.isSelected() ? "Nam" : (RadioNu.isSelected() ? "Nữ" : "Khác"));
            stmt.setString(7, txt_KhachHang_maKhachHang.getText());
            stmt.executeUpdate();
            loadKhachHangData(); // Cập nhật lại bảng
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_KhachHang_SuaActionPerformed

    private void btn_KhachHang_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHang_XoaActionPerformed
        try (Connection conn = modelConnectSQLServer.connectSQLServer()) {
        String query = "DELETE FROM KhachHang WHERE MaKH = ?";
        PreparedStatement stmt = conn.prepareStatement(query);
        stmt.setString(1, txt_KhachHang_maKhachHang.getText());
        stmt.executeUpdate();
        loadKhachHangData(); // Cập nhật lại bảng
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_KhachHang_XoaActionPerformed

    private void btn_KhachHang_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHang_TimKiemActionPerformed
        DefaultTableModel model = (DefaultTableModel) tb_KhachHang.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        try (Connection conn = modelConnectSQLServer.connectSQLServer()) {
            String query = "SELECT maKH , tenKH, SDT, Email, soDuTaiKhoan, diaChi, gioiTinh FROM KhachHang WHERE tenKH LIKE ? OR SDT LIKE ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, txt_KhachHang_TimKiemTen.getText());
            stmt.setString(2, txt_KhachHang_TimKiemSDT.getText() );
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maKH"),
                    rs.getString("tenKH"),
                    rs.getString("SDT"),
                    rs.getString("Email"),
                    rs.getInt("soDuTaiKhoan"),
                    rs.getString("diaChi"),
                    rs.getString("gioiTinh")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_KhachHang_TimKiemActionPerformed

    private void btn_KhachHang_ResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHang_ResertActionPerformed
        // Xóa dữ liệu trong các trường nhập liệu
        txt_KhachHang_maKhachHang.setText("");
        txt_KhachHang_tenKhachHang.setText("");
        txt_KhachHang_DiaChi.setText("");
        txt_KhachHang_SDT.setText("");
        txt_KhachHang_soDuTaiKhoan.setText("");
        txt_KhachHang_soDuTaiKhoan.setText("");
        
        txt_KhachHang_TimKiemTen.setText("");
        txt_KhachHang_TimKiemSDT.setText("");
        txt_KhachHang_Email.setText("");
        btnGr_GioiTinh.clearSelection();
        

        // Làm mới bảng dữ liệu
        loadKhachHangData();
    }//GEN-LAST:event_btn_KhachHang_ResertActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LayoutKhachHang;
    private javax.swing.JRadioButton RadioKhac;
    private javax.swing.JRadioButton RadioNam;
    private javax.swing.JRadioButton RadioNu;
    private javax.swing.ButtonGroup btnGr_GioiTinh;
    private javax.swing.JButton btn_KhachHang_Resert;
    private javax.swing.JButton btn_KhachHang_Sua;
    private javax.swing.JButton btn_KhachHang_Them;
    private javax.swing.JButton btn_KhachHang_TimKiem;
    private javax.swing.JButton btn_KhachHang_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel panel_timKiem;
    private javax.swing.JTable tb_KhachHang;
    private javax.swing.JTextField txt_KhachHang_DiaChi;
    private javax.swing.JTextField txt_KhachHang_Email;
    private javax.swing.JTextField txt_KhachHang_SDT;
    private javax.swing.JTextField txt_KhachHang_TimKiemSDT;
    private javax.swing.JTextField txt_KhachHang_TimKiemTen;
    private javax.swing.JTextField txt_KhachHang_maKhachHang;
    private javax.swing.JTextField txt_KhachHang_soDuTaiKhoan;
    private javax.swing.JTextField txt_KhachHang_tenKhachHang;
    // End of variables declaration//GEN-END:variables
}
