/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.btcuoiki_nhom.View;

import Model.modelConnectSQLServer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class LayoutNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form LayoutNhanVien
     */
    public LayoutNhanVien() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        loadNhanVienData(); // Gọi phương thức hiển thị dữ liệu
            btn_NhanVien_Them.addActionListener(evt -> btn_NhanVien_ThemActionPerformed(evt));
            btn_NhanVien_Sua.addActionListener(evt -> btn_NhanVien_SuaActionPerformed(evt));
            btn_NhanVien_Xoa.addActionListener(evt -> btn_NhanVien_XoaActionPerformed(evt));
            btn_NhanVien_TimKiem.addActionListener(evt -> btn_NhanVien_TimKiemActionPerformed(evt));
            btn_NhanVien_Resert.addActionListener(evt -> btn_NhanVien_ResertActionPerformed(evt));
    }
     private void loadNhanVienData() {
        DefaultTableModel model = (DefaultTableModel) tb_NhanVien.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ
        try (Connection conn = modelConnectSQLServer.connectSQLServer()) {
            String query = "SELECT * FROM NhanVien";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                System.out.println("Dữ liệu: " + rs.getString("MaNhanVien") + ", " + rs.getString("TenNhanVien"));
                model.addRow(new Object[]{
                    rs.getInt("STT"),
                    rs.getString("MaNhanVien"),
                    rs.getString("TenNhanVien"),
                    rs.getString("NgaySinh"),
                    rs.getString("GioiTinh"),
                    rs.getString("NgayVaoLam"),
                    rs.getString("ChucVu"),
                    rs.getString("DiaChi"),
                    rs.getString("SDT"),
                    rs.getString("ChuThich")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayoutNhanVien = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tb_NhanVien = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_NhanVien_maNhanVien = new javax.swing.JTextField();
        txt_NhanVien_TenNV = new javax.swing.JTextField();
        NgayVao_Day = new javax.swing.JComboBox<>();
        NgayVao_Month = new javax.swing.JComboBox<>();
        NgayVao_Year = new javax.swing.JComboBox<>();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txt_NhanVien_DiaChi = new javax.swing.JTextField();
        cb_NhanVien_ChucVu = new javax.swing.JComboBox<>();
        txt_NhanVien_SDT = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        txt_NhanVien_ChuThich = new javax.swing.JTextArea();
        btn_NhanVien_Them = new javax.swing.JButton();
        btn_NhanVien_Sua = new javax.swing.JButton();
        btn_NhanVien_Xoa = new javax.swing.JButton();
        btn_NhanVien_Resert = new javax.swing.JButton();
        jComboBox19 = new javax.swing.JComboBox<>();
        jTextField25 = new javax.swing.JTextField();
        btn_NhanVien_TimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Giới tính", "Ngày vào làm", "Chức Vụ", "Địa chỉ", "SĐT", "Chú Thích"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane11.setViewportView(tb_NhanVien);

        jLabel41.setText("Mã nhân viên");

        jLabel42.setText("Tên nhân viên");

        jLabel43.setText("ngày vào làm");

        jLabel44.setText("Giới tính ");

        jRadioButton7.setText("Nam");

        jRadioButton8.setText("Nữ");

        jLabel46.setText("Chức vụ");

        jLabel47.setText("Địa chỉ");

        jLabel48.setText("SĐT");

        jLabel49.setText("Chú thích");

        txt_NhanVien_ChuThich.setColumns(20);
        txt_NhanVien_ChuThich.setRows(5);
        jScrollPane12.setViewportView(txt_NhanVien_ChuThich);

        btn_NhanVien_Them.setText("Thêm");
        btn_NhanVien_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVien_ThemActionPerformed(evt);
            }
        });

        btn_NhanVien_Sua.setText("Sửa");
        btn_NhanVien_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVien_SuaActionPerformed(evt);
            }
        });

        btn_NhanVien_Xoa.setText("Xoá");
        btn_NhanVien_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVien_XoaActionPerformed(evt);
            }
        });

        btn_NhanVien_Resert.setText("Resert");
        btn_NhanVien_Resert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVien_ResertActionPerformed(evt);
            }
        });

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Họ và tên", "Chức Vụ ", "Giới Tính" }));

        btn_NhanVien_TimKiem.setText("Tìm kiếm");
        btn_NhanVien_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVien_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(NgayVao_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NgayVao_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NgayVao_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_NhanVien_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NhanVien_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(jLabel46)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49))
                .addGap(36, 36, 36)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_NhanVien_ChucVu, 0, 203, Short.MAX_VALUE)
                    .addComponent(txt_NhanVien_DiaChi)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addComponent(txt_NhanVien_SDT))
                .addGap(157, 157, 157)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_NhanVien_Resert)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_NhanVien_Xoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_NhanVien_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_NhanVien_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(174, 174, 174)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(btn_NhanVien_TimKiem)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(178, 178, 178))
        );

        jPanel13Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_NhanVien_Resert, btn_NhanVien_Them, btn_NhanVien_Xoa});

        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txt_NhanVien_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(cb_NhanVien_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NhanVien_Them)
                    .addComponent(btn_NhanVien_TimKiem))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(txt_NhanVien_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(txt_NhanVien_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_NhanVien_Sua)
                            .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel43)
                                .addComponent(NgayVao_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NgayVao_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NgayVao_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel48)
                                    .addComponent(txt_NhanVien_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_NhanVien_Xoa)))
                .addGap(7, 7, 7)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NhanVien_Resert))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout LayoutNhanVienLayout = new javax.swing.GroupLayout(LayoutNhanVien);
        LayoutNhanVien.setLayout(LayoutNhanVienLayout);
        LayoutNhanVienLayout.setHorizontalGroup(
            LayoutNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayoutNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LayoutNhanVienLayout.setVerticalGroup(
            LayoutNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutNhanVienLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1541, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LayoutNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LayoutNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_NhanVien_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVien_ThemActionPerformed
        try (Connection conn = modelConnectSQLServer.connectSQLServer()) {
        String query = "UPDATE NhanVien SET TenNhanVien = ?, NgaySinh = ?, GioiTinh = ?, NgayVaoLam = ?, ChucVu = ?, DiaChi = ?, SDT = ?, ChuThich = ? WHERE MaNhanVien = ?";
        PreparedStatement stmt = conn.prepareStatement(query);
        stmt.setString(1, txt_NhanVien_TenNV.getText());
        stmt.setString(2, "2025-04-20"); // Thay bằng giá trị từ ComboBox
        stmt.setString(3, jRadioButton7.isSelected() ? "Nam" : "Nữ");
        stmt.setString(4, "2025-04-20"); // Thay bằng giá trị từ ComboBox
        stmt.setString(5, cb_NhanVien_ChucVu.getSelectedItem().toString());
        stmt.setString(6, txt_NhanVien_DiaChi.getText());
        stmt.setString(7, txt_NhanVien_SDT.getText());
        stmt.setString(8, txt_NhanVien_ChuThich.getText());
        stmt.setString(9, txt_NhanVien_maNhanVien.getText());
        stmt.executeUpdate();
        loadNhanVienData(); // Cập nhật lại bảng
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_NhanVien_ThemActionPerformed

    private void btn_NhanVien_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVien_SuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NhanVien_SuaActionPerformed

    private void btn_NhanVien_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVien_XoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NhanVien_XoaActionPerformed

    private void btn_NhanVien_ResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVien_ResertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NhanVien_ResertActionPerformed

    private void btn_NhanVien_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVien_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NhanVien_TimKiemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LayoutNhanVien;
    private javax.swing.JComboBox<String> NgayVao_Day;
    private javax.swing.JComboBox<String> NgayVao_Month;
    private javax.swing.JComboBox<String> NgayVao_Year;
    private javax.swing.JButton btn_NhanVien_Resert;
    private javax.swing.JButton btn_NhanVien_Sua;
    private javax.swing.JButton btn_NhanVien_Them;
    private javax.swing.JButton btn_NhanVien_TimKiem;
    private javax.swing.JButton btn_NhanVien_Xoa;
    private javax.swing.JComboBox<String> cb_NhanVien_ChucVu;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTable tb_NhanVien;
    private javax.swing.JTextArea txt_NhanVien_ChuThich;
    private javax.swing.JTextField txt_NhanVien_DiaChi;
    private javax.swing.JTextField txt_NhanVien_SDT;
    private javax.swing.JTextField txt_NhanVien_TenNV;
    private javax.swing.JTextField txt_NhanVien_maNhanVien;
    // End of variables declaration//GEN-END:variables
}
