/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.btcuoiki_nhom.View;

/**
 *
 * @author Hieu
 */
public class mainGiaoDien extends javax.swing.JFrame {
    private LayoutDoiTac layoutDoiTac ;
    private LayoutHoaDon layoutHoaDon ;
    private LayoutKhachHang layoutKhachHang ;
    private LayoutNhanVien layoutNhanVien ;
    private LayoutSanPham layoutSanPham ;
    /**
     * Creates new form mainGiaoDien
     */
  
    public mainGiaoDien() {
        initComponents();
        
        this.layoutDoiTac = new LayoutDoiTac();
        this.layoutHoaDon = new LayoutHoaDon();
        this.layoutKhachHang = new LayoutKhachHang();
        this.layoutNhanVien = new LayoutNhanVien();
        this.layoutSanPham = new LayoutSanPham();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayoutDanhMuc = new javax.swing.JPanel();
        btn_HoaDon = new javax.swing.JButton();
        btn_KhachHang = new javax.swing.JButton();
        btn_NhanVien = new javax.swing.JButton();
        btn_DoiTac = new javax.swing.JButton();
        btn_SanPham = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_HoaDon.setText("Hoá Đơn");
        btn_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HoaDonActionPerformed(evt);
            }
        });

        btn_KhachHang.setText("Khách Hàng");
        btn_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHangActionPerformed(evt);
            }
        });

        btn_NhanVien.setText("Nhân Viên");
        btn_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVienActionPerformed(evt);
            }
        });

        btn_DoiTac.setText("Đối Tác");
        btn_DoiTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoiTacActionPerformed(evt);
            }
        });

        btn_SanPham.setText("Sản Phẩm");
        btn_SanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutDanhMucLayout = new javax.swing.GroupLayout(LayoutDanhMuc);
        LayoutDanhMuc.setLayout(LayoutDanhMucLayout);
        LayoutDanhMucLayout.setHorizontalGroup(
            LayoutDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutDanhMucLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(LayoutDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_DoiTac)
                    .addComponent(btn_NhanVien)
                    .addComponent(btn_KhachHang)
                    .addComponent(btn_SanPham)
                    .addComponent(btn_HoaDon))
                .addGap(32, 32, 32))
        );

        LayoutDanhMucLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_DoiTac, btn_HoaDon, btn_KhachHang, btn_NhanVien, btn_SanPham});

        LayoutDanhMucLayout.setVerticalGroup(
            LayoutDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutDanhMucLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btn_HoaDon)
                .addGap(59, 59, 59)
                .addComponent(btn_SanPham)
                .addGap(34, 34, 34)
                .addComponent(btn_KhachHang)
                .addGap(67, 67, 67)
                .addComponent(btn_NhanVien)
                .addGap(64, 64, 64)
                .addComponent(btn_DoiTac)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LayoutDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(616, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LayoutDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HoaDonActionPerformed
         layoutDoiTac.setVisible(false);
         this.layoutHoaDon.setVisible(true);
        this.layoutKhachHang.setVisible(false); 
        this.layoutNhanVien.setVisible(false); 
        this.layoutSanPham.setVisible(false); 
         
    }//GEN-LAST:event_btn_HoaDonActionPerformed

    private void btn_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHangActionPerformed
        layoutDoiTac.setVisible(false);
         this.layoutHoaDon.setVisible(false);   
        this.layoutKhachHang.setVisible(true); 
        this.layoutNhanVien.setVisible(false); 
        this.layoutSanPham.setVisible(false); 
    }//GEN-LAST:event_btn_KhachHangActionPerformed

    private void btn_SanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SanPhamActionPerformed
        layoutDoiTac.setVisible(false);
         this.layoutHoaDon.setVisible(false);
        this.layoutKhachHang.setVisible(false); 
        this.layoutNhanVien.setVisible(false); 
        this.layoutSanPham.setVisible(true); 
    }//GEN-LAST:event_btn_SanPhamActionPerformed

    private void btn_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVienActionPerformed
        layoutDoiTac.setVisible(false);
         this.layoutHoaDon.setVisible(false);
        this.layoutKhachHang.setVisible(false); 
        this.layoutNhanVien.setVisible(true); 
        this.layoutSanPham.setVisible(false); 
    }//GEN-LAST:event_btn_NhanVienActionPerformed

    private void btn_DoiTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoiTacActionPerformed
        layoutDoiTac.setVisible(true);
         this.layoutHoaDon.setVisible(false);
        this.layoutKhachHang.setVisible(false); 
        this.layoutNhanVien.setVisible(false); 
        this.layoutSanPham.setVisible(false); 
    }//GEN-LAST:event_btn_DoiTacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGiaoDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LayoutDanhMuc;
    private javax.swing.JButton btn_DoiTac;
    private javax.swing.JButton btn_HoaDon;
    private javax.swing.JButton btn_KhachHang;
    private javax.swing.JButton btn_NhanVien;
    private javax.swing.JButton btn_SanPham;
    // End of variables declaration//GEN-END:variables
}
